http:
  routers:
    api-v1-documentos:
      rule: "Host(`documentos.universidad.localhost`) && PathPrefix(`/api/v1`)"
      service: documentos-service
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - rate-limit
        - secure-headers

  services:
    documentos-service:
      loadBalancer:
        healthCheck:
          path: /api/v1/
          interval: 10s
          timeout: 3s